### PR TITLE
fix nonexistent level

### PR DESCRIPTION
**Pull request by Naleksuh**

### CODE REVIEW

**Comment by Naleksuh** [comment]
Just visited this repo (I was under the impression P2SM had been discontinued, but I guess it's back?) and saw the commit @mlugg  made which changed "disconnect" to "changelevel credits" (which doesn't exist)

**Comment by mlugg** [comment]
This map does exist, if it doesn't for you then you've installed the mod wrong.

**Comment by Naleksuh** [comment]
Sorry, my mistake. I was looking in the core map files. Though, @mlugg do you know anything about this mod being "un-discontinued"? I was under the impression this mod had been discontinued, though I was recently told by the creator of reverse mod that it was now being hosted here

**Comment by PortalRex** [comment]
The mod is being maintained here on the p2sr organization github yes, as it is more centralized with everything else. People are open to making pull requests for more features/game modes but I do not believe Krzyhau has any interest in further development.

**Pull request closed without merging**
